spring:
  application:
    name: ratingmicroservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce

server:
  port: 8081

jwt:
  secret: hellooooThisIsMySecretYarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
  expiration: 86400000  # 24 hours in ms