spring:
  application:
    name: ratingmicroservice
  data:
    mongodb:
      uri: ${MONGO_URI}
#      host: ${DB_HOST}
#      port: ${DB_PORT}
#      database: ${DB_NAME}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}